name: "LLM Code Reviewer"
description: "This GitHub Action automatically reviews PRs using multiple models."
author: 'tusgino'

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  GITEA_TOKEN:
    description: 'Gitea token to interact with the repository'
    required: true
  GITEA_URL:
    description: 'Gitea URL to interact with the repository'
    required: true
  OPENAI_BASE_URL:
    description: 'AI URL to interact with the repository'
    required: true
  API_KEY:
    description: 'AI API key'
    required: false
  AI_MODEL:
    description: 'The AI model to use for code review'
    required: false
    default: 'gpt-4o'
  INPUT_EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''
  HUMAN_LANGUAGE:
    description: 'The human language to use for code review'
    required: false

runs:
  using: docker
  image: Dockerfile
  env:
        GITEA_TOKEN: ${{ inputs.GITEA_TOKEN }}
        GITEA_URL: ${{ inputs.GITEA_URL }}
        OPENAI_BASE_URL: ${{ inputs.OPENAI_BASE_URL }}
        API_KEY: ${{ inputs.API_KEY }}
        AI_MODEL: ${{ inputs.AI_MODEL }}
        INPUT_EXCLUDE: ${{ inputs.INPUT_EXCLUDE }}
        HUMAN_LANGUAGE: ${{ inputs.HUMAN_LANGUAGE }}